from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from app.db.models.job_bookmark import JobBookmark
from app.db.models.job_listing import JobListing
from app.db.models.job_source import JobSource
from app.db.models.raw_job import RawJob
from app.db.models.scrape_run import ScrapeRun
from app.db.models.source_profile import SourceProfile


@dataclass(slots=True)
class JobListingFilters:
    source_id: int | None = None
    is_active: bool | None = None
    work_mode: str | None = None
    location: str | None = None
    title_query: str | None = None
    posted_from: datetime | None = None
    posted_to: datetime | None = None


class SourceProfileRepository(Protocol):
    def list_all(self) -> list[SourceProfile]: ...
    def list_active(self) -> list[SourceProfile]: ...
    def get(self, profile_id: int) -> SourceProfile | None: ...
    def get_by_code(self, code: str) -> SourceProfile | None: ...


class JobSourceRepository(Protocol):
    def create(self, source: JobSource) -> JobSource: ...
    def get(self, source_id: int) -> JobSource | None: ...
    def list_all(self) -> list[JobSource]: ...
    def list_enabled(self) -> list[JobSource]: ...
    def list_by_ids(self, source_ids: list[int]) -> list[JobSource]: ...
    def update(self, source: JobSource) -> JobSource: ...
    def delete(self, source_id: int) -> bool: ...


class ScrapeRunRepository(Protocol):
    def create(self, run: ScrapeRun) -> ScrapeRun: ...
    def get(self, run_id: int) -> ScrapeRun | None: ...
    def list_recent(self, limit: int = 50) -> list[ScrapeRun]: ...
    def update(self, run: ScrapeRun) -> ScrapeRun: ...


class RawJobRepository(Protocol):
    def create(self, raw_job: RawJob) -> RawJob: ...
    def list_by_run(self, scrape_run_id: int) -> list[RawJob]: ...


class JobListingRepository(Protocol):
    def create(self, listing: JobListing) -> JobListing: ...
    def get(self, listing_id: int) -> JobListing | None: ...
    def get_by_canonical_key(self, canonical_key: str) -> JobListing | None: ...
    def list_filtered(self, filters: JobListingFilters, limit: int = 100, offset: int = 0) -> list[JobListing]: ...
    def update(self, listing: JobListing) -> JobListing: ...


class JobBookmarkRepository(Protocol):
    def upsert(self, bookmark: JobBookmark) -> JobBookmark: ...
    def get_by_job_id(self, job_id: int) -> JobBookmark | None: ...
    def list_by_job_ids(self, job_ids: list[int]) -> list[JobBookmark]: ...
